### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by vegarringdal** [vegarringdal/aureliaGrid#15]
Little todo/add list
- [x] Add option to keep selection still of you have filtered away the rows that is selected.
- This way you can filter, highligh more/other rows

---
- [x] Tabbing between cells.
- when at the last cell it will just to next row, and that will become the current entity

---
- [ ] Support remote data
- to do this I will need to expose the getDataElement, collectionLength, onFilter, onSorting, so sorting/filter can be sent to remote server, reason for the collection lenght need to be exposed is if using virtual scrolling an not paging then you will need to respond with length of collection for server side, using virtual scrolling can be cool, but code for caching etc not so fun..
  try and set up a redhat shift node so I can try and play with this

> Update 23.04.2016:

Openshift server created: https://github.com/vegarringdal/redhatgear
Will haveto ha a look at some client side code:
*http://aurelia-orm.spoonx.org/
*http://aurelia-api.spoonx.org/

---
- [ ] rebuild parts of vGridGenerator so it uses viewCompiler and viewslots for the rows

> Update 23.04.2016:

Got the basics working, its displaying data, re size column, drag drop working
Tabbing is really messed up, but plan is to create some custom elements for cells so I have more control

> 25.04.2016

Demo up an runing what what Ive got for now, its faster then the old one on scrolling
http://vegarringdal.github.io/vGrid/viewSlotsDemo001/

> 26.04.2016

Created own repo for it
https://github.com/vegarringdal/vGrid/tree/dev-rebuild

**Comment by vegarringdal** [comment]
Closing this for now, having own issue for the rebuild...
