### ISSUE TITLE
Rebuild/ road map status (for V.1.0.0)

### ISSUE THREAD

**Issue by vegarringdal** [vegarringdal/aureliaGrid#30]
Progress/what to do (chrome, edge, ff)
**Version 1.0.0**
- [x] convert v-grid element attributes to Aurelia attributes so its not so messy
- [x] convert v-grid-col element attributes to Aurelia attributes so its not so messy
- [x] create own cell-row element
- [x] add checkbox to cell element
- [x] add image to cell element
- [x] move sortable logic out of vGridGenerator
- [x] move resizablecolumns logic out of vGridGenerator
- [x] make tabbing work/cell focus
- [x] make page /up work
- [x] clear all junk code from v-grid.js into the other cells
- [x] create own cell header element
- [x] clean up cell header element (make this act as contains for custom element inside it )
- [x] option to use value formater for display
- [x] improve valueformating, when edit mode it need to have option for displaying raw value/rawvalue formating..
- [x] try and replace selection logic with a set, and have option to defined index in collection it can use instead of creating own one.
- [x] before render event, to simplify how you make the grid, and for loading existing setup (all configs except 3 manadatory can be set in the gridcontext object)
- [x] option for on row click (return attribute and row)
- [x] option for on row dbl click (return attribute and row)
- [x] clean up v-grid-row-cell to be v-grid-row-col and act as a container for custom elements
- [x] make the context menus optional
- [x] clean up scrollerlogic  "onNormalScrolling" & "onNormalScrollingLarge" a lot of junk here
- [X] create wiki (started, main parts covered)
- [x] grid context into new class, and dont share the vGridGenerator, this will make in a lot cleaner
- [ ] debug/test for errors/clean up code/naming

Request for v1:
- [x] look at spesial col for highlight, manual selection, not the default used by grid

**Maybe v1/future version:**
- [x] new element that replace row, and just repeat what ever html is put in it
- expose the filter/sort functions so it can be used with remote server. 
- odata query/sorting string to make odata more easly to use? (question from gitter, but I dont know anything about oData... exposing the filter/sort then people should be able to fit it to thir needs)
- make into plugin
- maybe do grouping  ? dunno how but worth looking into
- look into how to use datepicker with it, need to test/ask around, maybe just add option for dataepicker in coltype, and use can supply/modify a element I set up and include their own datepicker

Please come with suggestions

[last commit before rebuild](https://github.com/vegarringdal/vGrid/commit/b503c2d56dc7d99aaf6fb93b893f89f6aee0f26b)

**Comment by vegarringdal** [comment]
will create separate issues from now.
