### ISSUE TITLE
Todo on new rebuild:

### ISSUE THREAD

**Issue by vegarringdal** [vegarringdal/aureliaGrid#50]
**grid**
* [x] convert it all to typescript (working, typings will need improvement)
* [x] Make into plugin 
* [ ] show/hide columns in menu
* [ ] make it possible to have custom html for the grouping
* [x] repeat html, for just repeating html inside a row that is 100% width
* [x] set columns by binding a column config array instead of using html to define columns
* [ ] add old key-move attribute for page up/down, tabbing
* [x] tempRef & rowdraw(attribute/callback/function)
* [x] group by with right click/menu

**gridconnector**
* [ ] able to replace gridconnector with custom one (need interface)
* [ ] option for gridconnector not to display anything by default
* [ ] option for setting scrollHeight on display, so it looks better when using mast/detail

**datasource**
* [ ] own datasource for remote data ("remote-datasource"), something simple where you define callbacks for filter/sort
* [ ] able to replace datasource  with custom one (need interface)
* [ ] addElements()
* [ ] replaceArray()

Todo...add more here
a lot other minor things thats buggy atm

**Comment by vegarringdal** [comment]
closing this, and add individual issues instead
